### ISSUE TITLE
HttpResponse.headers is empty 

### ISSUE THREAD

**Issue by bodeg** [DanWahlin/AngularCLI-ASPNET-Core-CustomersService#15]
When running Angular separately the returned HttpResponse.headers is empty 
so - getCustomersPage returns totalRecords (x-InlineCount ) = 0

what am I doing wrong?

**Comment by bodeg** [comment]
solved after I added

`Response.Headers.Add("Access-Control-Expose-Headers", "X-InlineCount");`

to CustomersApiController.CustomersPage

See also,
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

**Comment by DanWahlin** [comment]
Thanks for the heads-up there. I didn't realize header wasn't being surfaced to the Angular client in that scenario.

You can handle that across the entire app using the CORS middleware. I've updated Startup.cs to handle that now.
