### ISSUE TITLE
OverlayRequestResponseInterceptor

### ISSUE THREAD

**Issue by bodeg** [DanWahlin/AngularCLI-ASPNET-Core-CustomersService#16]
Thanks for the great work!

I had to change  
`OverlayRequestResponseInterceptor.intercept`

Once I added an HTTP interceptor to handle HTTP errors the overlay interceptor masked the http errors...

the following is my version

```
intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    this.eventBus.emit(new EmitEvent(Events.httpRequest));
    return next.handle(req)
      .pipe(
        finalize(() => this.eventBus.emit(new EmitEvent(Events.httpResponse)))
      );
}
```

alon.

**Comment by bodeg** [comment]
Ooopss my mistake - I should post it to  Angular-JumpStart

**Comment by DanWahlin** [comment]
If you're able to submit a pull request to the Angular-JumpStart repo that'd be great. Thanks.
