### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by StellarMLS** [DanWahlin/AngularCLI-ASPNET-Core-CustomersService#2]
Hi Dan,

I was following your pluralsight class and download the package and got a few errors after I restore all the client and server packages.  I had to install typescript Compiler and typescript MSBuild 2.7.2 and then the errors notification go away for VS 2017.  However, the package run fine without these two nuget packages but I hate seeing error notification in Visual Studio.

**Comment by DanWahlin** [comment]
Glad you got it going! If you didn’t have the typescript compiler it would definitely give an error (but should still run as you mentioned). I believe the latest updates to VS include that but I’d have to double check.
